### ISSUE TITLE
关于如何插入到模型中

### ISSUE THREAD

**Issue by Dengts821** [TaoShi1998/SSLCL#5]
你好，我想问一下，如何将这文件中这两个模型按论文所说的方法插入到任一模型中。我不知道怎么操作，插入网络后，标签嵌入没有发生改变，模型性能也没有发生变化。

**Comment by Dengts821** [comment]
> 你好，我想问一下，如何将这文件中这两个模型按论文所说的方法插入到任一模型中。我不知道怎么操作，插入网络后，标签嵌入没有发生改变，模型性能也没有发生变化。

**Comment by jellyfishovo** [comment]
你好，请问你解决了吗，我在插入这个loss的时候，无法得到合理的label embedding，我的label形状是(bs * seq_len, 1)，根据代码无法得到正确形状的embeddings
